version: '3'

services:

  ubuntu:
    container_name: machine_learning_2
    image: machine_learning_2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8888:8888
    volumes:
    - ./:/shared:z

